/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface Message : NSObject <TBase, NSCoding> {
  NSString * __text;
  NSString * __date;

  BOOL __text_isset;
  BOOL __date_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=text, setter=setText:) NSString * text;
@property (nonatomic, retain, getter=date, setter=setDate:) NSString * date;
#endif

- (id) init;
- (id) initWithText: (NSString *) text date: (NSString *) date;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) text;
- (void) setText: (NSString *) text;
#endif
- (BOOL) textIsSet;

#if !__has_feature(objc_arc)
- (NSString *) date;
- (void) setDate: (NSString *) date;
#endif
- (BOOL) dateIsSet;

@end

@interface testConstants : NSObject {
}
@end
