/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


@interface SuppliesOrder : NSObject <NSCoding> {
  int32_t __supplyId;
  int32_t __quantity;
  double __price;

  BOOL __supplyId_isset;
  BOOL __quantity_isset;
  BOOL __price_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=supplyId, setter=setSupplyId:) int32_t supplyId;
@property (nonatomic, getter=quantity, setter=setQuantity:) int32_t quantity;
@property (nonatomic, getter=price, setter=setPrice:) double price;
#endif

- (id) init;
- (id) initWithSupplyId: (int32_t) supplyId quantity: (int32_t) quantity price: (double) price;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int32_t) supplyId;
- (void) setSupplyId: (int32_t) supplyId;
#endif
- (BOOL) supplyIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) quantity;
- (void) setQuantity: (int32_t) quantity;
#endif
- (BOOL) quantityIsSet;

#if !__has_feature(objc_arc)
- (double) price;
- (void) setPrice: (double) price;
#endif
- (BOOL) priceIsSet;

@end

@interface RefundCouponConsumption : NSObject <NSCoding> {
  int64_t __refundCouponId;
  double __value;

  BOOL __refundCouponId_isset;
  BOOL __value_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=refundCouponId, setter=setRefundCouponId:) int64_t refundCouponId;
@property (nonatomic, getter=value, setter=setValue:) double value;
#endif

- (id) init;
- (id) initWithRefundCouponId: (int64_t) refundCouponId value: (double) value;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) refundCouponId;
- (void) setRefundCouponId: (int64_t) refundCouponId;
#endif
- (BOOL) refundCouponIdIsSet;

#if !__has_feature(objc_arc)
- (double) value;
- (void) setValue: (double) value;
#endif
- (BOOL) valueIsSet;

@end

@interface BookingRequest : NSObject <NSCoding> {
  int64_t __memberId;
  int32_t __hotelId;
  int32_t __roomId;
  int64_t __checkinTime;
  int64_t __checkoutTime;
  int32_t __roomNumber;
  NSMutableArray * __guest;
  NSString * __contactName;
  NSString * __contactPhone;
  NSMutableArray * __suppliesOrder;
  NSMutableArray * __refundCouponConsumption;
  int32_t __propertyId;
  int32_t __propertyType;
  int32_t __innSellerId;
  int32_t __innMarketId;

  BOOL __memberId_isset;
  BOOL __hotelId_isset;
  BOOL __roomId_isset;
  BOOL __checkinTime_isset;
  BOOL __checkoutTime_isset;
  BOOL __roomNumber_isset;
  BOOL __guest_isset;
  BOOL __contactName_isset;
  BOOL __contactPhone_isset;
  BOOL __suppliesOrder_isset;
  BOOL __refundCouponConsumption_isset;
  BOOL __propertyId_isset;
  BOOL __propertyType_isset;
  BOOL __innSellerId_isset;
  BOOL __innMarketId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=memberId, setter=setMemberId:) int64_t memberId;
@property (nonatomic, getter=hotelId, setter=setHotelId:) int32_t hotelId;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, getter=checkinTime, setter=setCheckinTime:) int64_t checkinTime;
@property (nonatomic, getter=checkoutTime, setter=setCheckoutTime:) int64_t checkoutTime;
@property (nonatomic, getter=roomNumber, setter=setRoomNumber:) int32_t roomNumber;
@property (nonatomic, retain, getter=guest, setter=setGuest:) NSMutableArray * guest;
@property (nonatomic, retain, getter=contactName, setter=setContactName:) NSString * contactName;
@property (nonatomic, retain, getter=contactPhone, setter=setContactPhone:) NSString * contactPhone;
@property (nonatomic, retain, getter=suppliesOrder, setter=setSuppliesOrder:) NSMutableArray * suppliesOrder;
@property (nonatomic, retain, getter=refundCouponConsumption, setter=setRefundCouponConsumption:) NSMutableArray * refundCouponConsumption;
@property (nonatomic, getter=propertyId, setter=setPropertyId:) int32_t propertyId;
@property (nonatomic, getter=propertyType, setter=setPropertyType:) int32_t propertyType;
@property (nonatomic, getter=innSellerId, setter=setInnSellerId:) int32_t innSellerId;
@property (nonatomic, getter=innMarketId, setter=setInnMarketId:) int32_t innMarketId;
#endif

- (id) init;
- (id) initWithMemberId: (int64_t) memberId hotelId: (int32_t) hotelId roomId: (int32_t) roomId checkinTime: (int64_t) checkinTime checkoutTime: (int64_t) checkoutTime roomNumber: (int32_t) roomNumber guest: (NSMutableArray *) guest contactName: (NSString *) contactName contactPhone: (NSString *) contactPhone suppliesOrder: (NSMutableArray *) suppliesOrder refundCouponConsumption: (NSMutableArray *) refundCouponConsumption propertyId: (int32_t) propertyId propertyType: (int32_t) propertyType innSellerId: (int32_t) innSellerId innMarketId: (int32_t) innMarketId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) memberId;
- (void) setMemberId: (int64_t) memberId;
#endif
- (BOOL) memberIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) hotelId;
- (void) setHotelId: (int32_t) hotelId;
#endif
- (BOOL) hotelIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
#endif
- (BOOL) roomIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checkinTime;
- (void) setCheckinTime: (int64_t) checkinTime;
#endif
- (BOOL) checkinTimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checkoutTime;
- (void) setCheckoutTime: (int64_t) checkoutTime;
#endif
- (BOOL) checkoutTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) roomNumber;
- (void) setRoomNumber: (int32_t) roomNumber;
#endif
- (BOOL) roomNumberIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) guest;
- (void) setGuest: (NSMutableArray *) guest;
#endif
- (BOOL) guestIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contactName;
- (void) setContactName: (NSString *) contactName;
#endif
- (BOOL) contactNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contactPhone;
- (void) setContactPhone: (NSString *) contactPhone;
#endif
- (BOOL) contactPhoneIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) suppliesOrder;
- (void) setSuppliesOrder: (NSMutableArray *) suppliesOrder;
#endif
- (BOOL) suppliesOrderIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) refundCouponConsumption;
- (void) setRefundCouponConsumption: (NSMutableArray *) refundCouponConsumption;
#endif
- (BOOL) refundCouponConsumptionIsSet;

#if !__has_feature(objc_arc)
- (int32_t) propertyId;
- (void) setPropertyId: (int32_t) propertyId;
#endif
- (BOOL) propertyIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) propertyType;
- (void) setPropertyType: (int32_t) propertyType;
#endif
- (BOOL) propertyTypeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) innSellerId;
- (void) setInnSellerId: (int32_t) innSellerId;
#endif
- (BOOL) innSellerIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) innMarketId;
- (void) setInnMarketId: (int32_t) innMarketId;
#endif
- (BOOL) innMarketIdIsSet;

@end

@interface ReservationRequest : NSObject <NSCoding> {
  int64_t __memberId;
  int64_t __reservationId;
  int32_t __hotelId;

  BOOL __memberId_isset;
  BOOL __reservationId_isset;
  BOOL __hotelId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=memberId, setter=setMemberId:) int64_t memberId;
@property (nonatomic, getter=reservationId, setter=setReservationId:) int64_t reservationId;
@property (nonatomic, getter=hotelId, setter=setHotelId:) int32_t hotelId;
#endif

- (id) init;
- (id) initWithMemberId: (int64_t) memberId reservationId: (int64_t) reservationId hotelId: (int32_t) hotelId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) memberId;
- (void) setMemberId: (int64_t) memberId;
#endif
- (BOOL) memberIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) reservationId;
- (void) setReservationId: (int64_t) reservationId;
#endif
- (BOOL) reservationIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) hotelId;
- (void) setHotelId: (int32_t) hotelId;
#endif
- (BOOL) hotelIdIsSet;

@end

@interface VoucherConsumption : NSObject <NSCoding> {
  int64_t __voucherId;
  double __value;

  BOOL __voucherId_isset;
  BOOL __value_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=voucherId, setter=setVoucherId:) int64_t voucherId;
@property (nonatomic, getter=value, setter=setValue:) double value;
#endif

- (id) init;
- (id) initWithVoucherId: (int64_t) voucherId value: (double) value;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) voucherId;
- (void) setVoucherId: (int64_t) voucherId;
#endif
- (BOOL) voucherIdIsSet;

#if !__has_feature(objc_arc)
- (double) value;
- (void) setValue: (double) value;
#endif
- (BOOL) valueIsSet;

@end

@interface Reservation : NSObject <NSCoding> {
  int64_t __reservationId;
  int32_t __status;
  int32_t __returnCode;
  int32_t __hotelId;
  NSString * __hotelName;
  NSString * __hotelAddress;
  NSString * __hotelPhone;
  int64_t __checkinTime;
  int64_t __checkoutTime;
  int32_t __roomId;
  NSString * __roomName;
  int32_t __roomNumber;
  NSMutableArray * __guest;
  NSString * __contactName;
  NSString * __contactPhone;
  NSMutableArray * __suppliesOrder;
  double __totalPrice;
  int32_t __paymentStatus;
  BOOL __cancelable;
  int64_t __keepOnLatestTime;

  BOOL __reservationId_isset;
  BOOL __status_isset;
  BOOL __returnCode_isset;
  BOOL __hotelId_isset;
  BOOL __hotelName_isset;
  BOOL __hotelAddress_isset;
  BOOL __hotelPhone_isset;
  BOOL __checkinTime_isset;
  BOOL __checkoutTime_isset;
  BOOL __roomId_isset;
  BOOL __roomName_isset;
  BOOL __roomNumber_isset;
  BOOL __guest_isset;
  BOOL __contactName_isset;
  BOOL __contactPhone_isset;
  BOOL __suppliesOrder_isset;
  BOOL __totalPrice_isset;
  BOOL __paymentStatus_isset;
  BOOL __cancelable_isset;
  BOOL __keepOnLatestTime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=reservationId, setter=setReservationId:) int64_t reservationId;
@property (nonatomic, getter=status, setter=setStatus:) int32_t status;
@property (nonatomic, getter=returnCode, setter=setReturnCode:) int32_t returnCode;
@property (nonatomic, getter=hotelId, setter=setHotelId:) int32_t hotelId;
@property (nonatomic, retain, getter=hotelName, setter=setHotelName:) NSString * hotelName;
@property (nonatomic, retain, getter=hotelAddress, setter=setHotelAddress:) NSString * hotelAddress;
@property (nonatomic, retain, getter=hotelPhone, setter=setHotelPhone:) NSString * hotelPhone;
@property (nonatomic, getter=checkinTime, setter=setCheckinTime:) int64_t checkinTime;
@property (nonatomic, getter=checkoutTime, setter=setCheckoutTime:) int64_t checkoutTime;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, retain, getter=roomName, setter=setRoomName:) NSString * roomName;
@property (nonatomic, getter=roomNumber, setter=setRoomNumber:) int32_t roomNumber;
@property (nonatomic, retain, getter=guest, setter=setGuest:) NSMutableArray * guest;
@property (nonatomic, retain, getter=contactName, setter=setContactName:) NSString * contactName;
@property (nonatomic, retain, getter=contactPhone, setter=setContactPhone:) NSString * contactPhone;
@property (nonatomic, retain, getter=suppliesOrder, setter=setSuppliesOrder:) NSMutableArray * suppliesOrder;
@property (nonatomic, getter=totalPrice, setter=setTotalPrice:) double totalPrice;
@property (nonatomic, getter=paymentStatus, setter=setPaymentStatus:) int32_t paymentStatus;
@property (nonatomic, getter=cancelable, setter=setCancelable:) BOOL cancelable;
@property (nonatomic, getter=keepOnLatestTime, setter=setKeepOnLatestTime:) int64_t keepOnLatestTime;
#endif

- (id) init;
- (id) initWithReservationId: (int64_t) reservationId status: (int32_t) status returnCode: (int32_t) returnCode hotelId: (int32_t) hotelId hotelName: (NSString *) hotelName hotelAddress: (NSString *) hotelAddress hotelPhone: (NSString *) hotelPhone checkinTime: (int64_t) checkinTime checkoutTime: (int64_t) checkoutTime roomId: (int32_t) roomId roomName: (NSString *) roomName roomNumber: (int32_t) roomNumber guest: (NSMutableArray *) guest contactName: (NSString *) contactName contactPhone: (NSString *) contactPhone suppliesOrder: (NSMutableArray *) suppliesOrder totalPrice: (double) totalPrice paymentStatus: (int32_t) paymentStatus cancelable: (BOOL) cancelable keepOnLatestTime: (int64_t) keepOnLatestTime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) reservationId;
- (void) setReservationId: (int64_t) reservationId;
#endif
- (BOOL) reservationIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) status;
- (void) setStatus: (int32_t) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (int32_t) returnCode;
- (void) setReturnCode: (int32_t) returnCode;
#endif
- (BOOL) returnCodeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) hotelId;
- (void) setHotelId: (int32_t) hotelId;
#endif
- (BOOL) hotelIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hotelName;
- (void) setHotelName: (NSString *) hotelName;
#endif
- (BOOL) hotelNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hotelAddress;
- (void) setHotelAddress: (NSString *) hotelAddress;
#endif
- (BOOL) hotelAddressIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hotelPhone;
- (void) setHotelPhone: (NSString *) hotelPhone;
#endif
- (BOOL) hotelPhoneIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checkinTime;
- (void) setCheckinTime: (int64_t) checkinTime;
#endif
- (BOOL) checkinTimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checkoutTime;
- (void) setCheckoutTime: (int64_t) checkoutTime;
#endif
- (BOOL) checkoutTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
#endif
- (BOOL) roomIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) roomName;
- (void) setRoomName: (NSString *) roomName;
#endif
- (BOOL) roomNameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) roomNumber;
- (void) setRoomNumber: (int32_t) roomNumber;
#endif
- (BOOL) roomNumberIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) guest;
- (void) setGuest: (NSMutableArray *) guest;
#endif
- (BOOL) guestIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contactName;
- (void) setContactName: (NSString *) contactName;
#endif
- (BOOL) contactNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contactPhone;
- (void) setContactPhone: (NSString *) contactPhone;
#endif
- (BOOL) contactPhoneIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) suppliesOrder;
- (void) setSuppliesOrder: (NSMutableArray *) suppliesOrder;
#endif
- (BOOL) suppliesOrderIsSet;

#if !__has_feature(objc_arc)
- (double) totalPrice;
- (void) setTotalPrice: (double) totalPrice;
#endif
- (BOOL) totalPriceIsSet;

#if !__has_feature(objc_arc)
- (int32_t) paymentStatus;
- (void) setPaymentStatus: (int32_t) paymentStatus;
#endif
- (BOOL) paymentStatusIsSet;

#if !__has_feature(objc_arc)
- (BOOL) cancelable;
- (void) setCancelable: (BOOL) cancelable;
#endif
- (BOOL) cancelableIsSet;

#if !__has_feature(objc_arc)
- (int64_t) keepOnLatestTime;
- (void) setKeepOnLatestTime: (int64_t) keepOnLatestTime;
#endif
- (BOOL) keepOnLatestTimeIsSet;

@end

@interface PayRequest : NSObject <NSCoding> {
  int64_t __memberId;
  int64_t __reservationId;
  int32_t __hotelId;
  NSMutableArray * __voucherConsumption;
  NSMutableArray * __refundCouponConsumption;
  double __storedValue;
  double __fastPayAmount;

  BOOL __memberId_isset;
  BOOL __reservationId_isset;
  BOOL __hotelId_isset;
  BOOL __voucherConsumption_isset;
  BOOL __refundCouponConsumption_isset;
  BOOL __storedValue_isset;
  BOOL __fastPayAmount_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=memberId, setter=setMemberId:) int64_t memberId;
@property (nonatomic, getter=reservationId, setter=setReservationId:) int64_t reservationId;
@property (nonatomic, getter=hotelId, setter=setHotelId:) int32_t hotelId;
@property (nonatomic, retain, getter=voucherConsumption, setter=setVoucherConsumption:) NSMutableArray * voucherConsumption;
@property (nonatomic, retain, getter=refundCouponConsumption, setter=setRefundCouponConsumption:) NSMutableArray * refundCouponConsumption;
@property (nonatomic, getter=storedValue, setter=setStoredValue:) double storedValue;
@property (nonatomic, getter=fastPayAmount, setter=setFastPayAmount:) double fastPayAmount;
#endif

- (id) init;
- (id) initWithMemberId: (int64_t) memberId reservationId: (int64_t) reservationId hotelId: (int32_t) hotelId voucherConsumption: (NSMutableArray *) voucherConsumption refundCouponConsumption: (NSMutableArray *) refundCouponConsumption storedValue: (double) storedValue fastPayAmount: (double) fastPayAmount;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) memberId;
- (void) setMemberId: (int64_t) memberId;
#endif
- (BOOL) memberIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) reservationId;
- (void) setReservationId: (int64_t) reservationId;
#endif
- (BOOL) reservationIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) hotelId;
- (void) setHotelId: (int32_t) hotelId;
#endif
- (BOOL) hotelIdIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) voucherConsumption;
- (void) setVoucherConsumption: (NSMutableArray *) voucherConsumption;
#endif
- (BOOL) voucherConsumptionIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) refundCouponConsumption;
- (void) setRefundCouponConsumption: (NSMutableArray *) refundCouponConsumption;
#endif
- (BOOL) refundCouponConsumptionIsSet;

#if !__has_feature(objc_arc)
- (double) storedValue;
- (void) setStoredValue: (double) storedValue;
#endif
- (BOOL) storedValueIsSet;

#if !__has_feature(objc_arc)
- (double) fastPayAmount;
- (void) setFastPayAmount: (double) fastPayAmount;
#endif
- (BOOL) fastPayAmountIsSet;

@end

@interface Payment : NSObject <NSCoding> {
}

- (id) init;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

@end

@interface AssetRequest : NSObject <NSCoding> {
  int64_t __memberId;
  int32_t __cityId;
  int32_t __hotelId;
  int32_t __roomId;
  int64_t __checkinTime;
  int64_t __checkoutTime;
  int32_t __pageIndex;
  int32_t __pageSize;

  BOOL __memberId_isset;
  BOOL __cityId_isset;
  BOOL __hotelId_isset;
  BOOL __roomId_isset;
  BOOL __checkinTime_isset;
  BOOL __checkoutTime_isset;
  BOOL __pageIndex_isset;
  BOOL __pageSize_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=memberId, setter=setMemberId:) int64_t memberId;
@property (nonatomic, getter=cityId, setter=setCityId:) int32_t cityId;
@property (nonatomic, getter=hotelId, setter=setHotelId:) int32_t hotelId;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, getter=checkinTime, setter=setCheckinTime:) int64_t checkinTime;
@property (nonatomic, getter=checkoutTime, setter=setCheckoutTime:) int64_t checkoutTime;
@property (nonatomic, getter=pageIndex, setter=setPageIndex:) int32_t pageIndex;
@property (nonatomic, getter=pageSize, setter=setPageSize:) int32_t pageSize;
#endif

- (id) init;
- (id) initWithMemberId: (int64_t) memberId cityId: (int32_t) cityId hotelId: (int32_t) hotelId roomId: (int32_t) roomId checkinTime: (int64_t) checkinTime checkoutTime: (int64_t) checkoutTime pageIndex: (int32_t) pageIndex pageSize: (int32_t) pageSize;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) memberId;
- (void) setMemberId: (int64_t) memberId;
#endif
- (BOOL) memberIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) cityId;
- (void) setCityId: (int32_t) cityId;
#endif
- (BOOL) cityIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) hotelId;
- (void) setHotelId: (int32_t) hotelId;
#endif
- (BOOL) hotelIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
#endif
- (BOOL) roomIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checkinTime;
- (void) setCheckinTime: (int64_t) checkinTime;
#endif
- (BOOL) checkinTimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checkoutTime;
- (void) setCheckoutTime: (int64_t) checkoutTime;
#endif
- (BOOL) checkoutTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) pageIndex;
- (void) setPageIndex: (int32_t) pageIndex;
#endif
- (BOOL) pageIndexIsSet;

#if !__has_feature(objc_arc)
- (int32_t) pageSize;
- (void) setPageSize: (int32_t) pageSize;
#endif
- (BOOL) pageSizeIsSet;

@end

@interface TBookingConstants : NSObject {
}
@end
