/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "THotel.h"
#import "TMember.h"
#import "TBooking.h"

@interface ClientInfo : NSObject <NSCoding> {
  NSString * __deviceId;
  NSString * __platform;
  NSString * __platformVersion;
  int32_t __appId;
  NSString * __version;
  NSString * __mpId;
  int64_t __lastUpdateTime;

  BOOL __deviceId_isset;
  BOOL __platform_isset;
  BOOL __platformVersion_isset;
  BOOL __appId_isset;
  BOOL __version_isset;
  BOOL __mpId_isset;
  BOOL __lastUpdateTime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=deviceId, setter=setDeviceId:) NSString * deviceId;
@property (nonatomic, retain, getter=platform, setter=setPlatform:) NSString * platform;
@property (nonatomic, retain, getter=platformVersion, setter=setPlatformVersion:) NSString * platformVersion;
@property (nonatomic, getter=appId, setter=setAppId:) int32_t appId;
@property (nonatomic, retain, getter=version, setter=setVersion:) NSString * version;
@property (nonatomic, retain, getter=mpId, setter=setMpId:) NSString * mpId;
@property (nonatomic, getter=lastUpdateTime, setter=setLastUpdateTime:) int64_t lastUpdateTime;
#endif

- (id) init;
- (id) initWithDeviceId: (NSString *) deviceId platform: (NSString *) platform platformVersion: (NSString *) platformVersion appId: (int32_t) appId version: (NSString *) version mpId: (NSString *) mpId lastUpdateTime: (int64_t) lastUpdateTime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) deviceId;
- (void) setDeviceId: (NSString *) deviceId;
#endif
- (BOOL) deviceIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) platform;
- (void) setPlatform: (NSString *) platform;
#endif
- (BOOL) platformIsSet;

#if !__has_feature(objc_arc)
- (NSString *) platformVersion;
- (void) setPlatformVersion: (NSString *) platformVersion;
#endif
- (BOOL) platformVersionIsSet;

#if !__has_feature(objc_arc)
- (int32_t) appId;
- (void) setAppId: (int32_t) appId;
#endif
- (BOOL) appIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) version;
- (void) setVersion: (NSString *) version;
#endif
- (BOOL) versionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) mpId;
- (void) setMpId: (NSString *) mpId;
#endif
- (BOOL) mpIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) lastUpdateTime;
- (void) setLastUpdateTime: (int64_t) lastUpdateTime;
#endif
- (BOOL) lastUpdateTimeIsSet;

@end

@interface ServerInfo : NSObject <NSCoding> {
  NSString * __minVersion;
  NSString * __latestVersion;
  NSString * __updateUrl;
  NSString * __cityListUrl;
  NSString * __regionListUrl;

  BOOL __minVersion_isset;
  BOOL __latestVersion_isset;
  BOOL __updateUrl_isset;
  BOOL __cityListUrl_isset;
  BOOL __regionListUrl_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=minVersion, setter=setMinVersion:) NSString * minVersion;
@property (nonatomic, retain, getter=latestVersion, setter=setLatestVersion:) NSString * latestVersion;
@property (nonatomic, retain, getter=updateUrl, setter=setUpdateUrl:) NSString * updateUrl;
@property (nonatomic, retain, getter=cityListUrl, setter=setCityListUrl:) NSString * cityListUrl;
@property (nonatomic, retain, getter=regionListUrl, setter=setRegionListUrl:) NSString * regionListUrl;
#endif

- (id) init;
- (id) initWithMinVersion: (NSString *) minVersion latestVersion: (NSString *) latestVersion updateUrl: (NSString *) updateUrl cityListUrl: (NSString *) cityListUrl regionListUrl: (NSString *) regionListUrl;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) minVersion;
- (void) setMinVersion: (NSString *) minVersion;
#endif
- (BOOL) minVersionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) latestVersion;
- (void) setLatestVersion: (NSString *) latestVersion;
#endif
- (BOOL) latestVersionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) updateUrl;
- (void) setUpdateUrl: (NSString *) updateUrl;
#endif
- (BOOL) updateUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cityListUrl;
- (void) setCityListUrl: (NSString *) cityListUrl;
#endif
- (BOOL) cityListUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) regionListUrl;
- (void) setRegionListUrl: (NSString *) regionListUrl;
#endif
- (BOOL) regionListUrlIsSet;

@end

@protocol ISevenDaysService <NSObject>
- (ServerInfo *) Startup: (ClientInfo *) clientInfo;  // throws TException
- (NSMutableArray *) searchHotel: (SearchRequest *) request;  // throws TException
- (Hotel *) getHotelDetails: (HotelRequest *) request;  // throws TException
- (NSMutableArray *) bookHotel: (BookingRequest *) request;  // throws TException
@end

@interface ISevenDaysServiceClient : NSObject <ISevenDaysService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ISevenDaysServiceProcessor : NSObject <TProcessor> {
  id <ISevenDaysService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithISevenDaysService: (id <ISevenDaysService>) service;
- (id<ISevenDaysService>) service;
@end

@interface ISevenDaysServiceConstants : NSObject {
}
@end
