/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


#import "TBooking.h"

@implementation SupplyOrder

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSupplyId: (int32_t) supplyId quantity: (int32_t) quantity
{
  self = [super init];
  __supplyId = supplyId;
  __supplyId_isset = YES;
  __quantity = quantity;
  __quantity_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"supplyId"])
  {
    __supplyId = [decoder decodeInt32ForKey: @"supplyId"];
    __supplyId_isset = YES;
  }
  if ([decoder containsValueForKey: @"quantity"])
  {
    __quantity = [decoder decodeInt32ForKey: @"quantity"];
    __quantity_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__supplyId_isset)
  {
    [encoder encodeInt32: __supplyId forKey: @"supplyId"];
  }
  if (__quantity_isset)
  {
    [encoder encodeInt32: __quantity forKey: @"quantity"];
  }
}

- (void) dealloc
{
  [super dealloc_stub];
}

- (int32_t) supplyId {
  return __supplyId;
}

- (void) setSupplyId: (int32_t) supplyId {
  __supplyId = supplyId;
  __supplyId_isset = YES;
}

- (BOOL) supplyIdIsSet {
  return __supplyId_isset;
}

- (void) unsetSupplyId {
  __supplyId_isset = NO;
}

- (int32_t) quantity {
  return __quantity;
}

- (void) setQuantity: (int32_t) quantity {
  __quantity = quantity;
  __quantity_isset = YES;
}

- (BOOL) quantityIsSet {
  return __quantity_isset;
}

- (void) unsetQuantity {
  __quantity_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setSupplyId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setQuantity: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"SupplyOrder"];
  if (__supplyId_isset) {
    [outProtocol writeFieldBeginWithName: @"supplyId" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __supplyId];
    [outProtocol writeFieldEnd];
  }
  if (__quantity_isset) {
    [outProtocol writeFieldBeginWithName: @"quantity" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __quantity];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"SupplyOrder("];
  [ms appendString: @"supplyId:"];
  [ms appendFormat: @"%i", __supplyId];
  [ms appendString: @",quantity:"];
  [ms appendFormat: @"%i", __quantity];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation BookingRequest

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithMemberId: (int64_t) memberId hotelId: (int32_t) hotelId roomId: (int32_t) roomId checkinTime: (int64_t) checkinTime checckoutTime: (int64_t) checckoutTime roomNumber: (int32_t) roomNumber guest: (NSMutableArray *) guest contactName: (NSString *) contactName contactPhone: (NSString *) contactPhone supplyOrder: (NSMutableArray *) supplyOrder
{
  self = [super init];
  __memberId = memberId;
  __memberId_isset = YES;
  __hotelId = hotelId;
  __hotelId_isset = YES;
  __roomId = roomId;
  __roomId_isset = YES;
  __checkinTime = checkinTime;
  __checkinTime_isset = YES;
  __checckoutTime = checckoutTime;
  __checckoutTime_isset = YES;
  __roomNumber = roomNumber;
  __roomNumber_isset = YES;
  __guest = [guest retain_stub];
  __guest_isset = YES;
  __contactName = [contactName retain_stub];
  __contactName_isset = YES;
  __contactPhone = [contactPhone retain_stub];
  __contactPhone_isset = YES;
  __supplyOrder = [supplyOrder retain_stub];
  __supplyOrder_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"memberId"])
  {
    __memberId = [decoder decodeInt64ForKey: @"memberId"];
    __memberId_isset = YES;
  }
  if ([decoder containsValueForKey: @"hotelId"])
  {
    __hotelId = [decoder decodeInt32ForKey: @"hotelId"];
    __hotelId_isset = YES;
  }
  if ([decoder containsValueForKey: @"roomId"])
  {
    __roomId = [decoder decodeInt32ForKey: @"roomId"];
    __roomId_isset = YES;
  }
  if ([decoder containsValueForKey: @"checkinTime"])
  {
    __checkinTime = [decoder decodeInt64ForKey: @"checkinTime"];
    __checkinTime_isset = YES;
  }
  if ([decoder containsValueForKey: @"checckoutTime"])
  {
    __checckoutTime = [decoder decodeInt64ForKey: @"checckoutTime"];
    __checckoutTime_isset = YES;
  }
  if ([decoder containsValueForKey: @"roomNumber"])
  {
    __roomNumber = [decoder decodeInt32ForKey: @"roomNumber"];
    __roomNumber_isset = YES;
  }
  if ([decoder containsValueForKey: @"guest"])
  {
    __guest = [[decoder decodeObjectForKey: @"guest"] retain_stub];
    __guest_isset = YES;
  }
  if ([decoder containsValueForKey: @"contactName"])
  {
    __contactName = [[decoder decodeObjectForKey: @"contactName"] retain_stub];
    __contactName_isset = YES;
  }
  if ([decoder containsValueForKey: @"contactPhone"])
  {
    __contactPhone = [[decoder decodeObjectForKey: @"contactPhone"] retain_stub];
    __contactPhone_isset = YES;
  }
  if ([decoder containsValueForKey: @"supplyOrder"])
  {
    __supplyOrder = [[decoder decodeObjectForKey: @"supplyOrder"] retain_stub];
    __supplyOrder_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__memberId_isset)
  {
    [encoder encodeInt64: __memberId forKey: @"memberId"];
  }
  if (__hotelId_isset)
  {
    [encoder encodeInt32: __hotelId forKey: @"hotelId"];
  }
  if (__roomId_isset)
  {
    [encoder encodeInt32: __roomId forKey: @"roomId"];
  }
  if (__checkinTime_isset)
  {
    [encoder encodeInt64: __checkinTime forKey: @"checkinTime"];
  }
  if (__checckoutTime_isset)
  {
    [encoder encodeInt64: __checckoutTime forKey: @"checckoutTime"];
  }
  if (__roomNumber_isset)
  {
    [encoder encodeInt32: __roomNumber forKey: @"roomNumber"];
  }
  if (__guest_isset)
  {
    [encoder encodeObject: __guest forKey: @"guest"];
  }
  if (__contactName_isset)
  {
    [encoder encodeObject: __contactName forKey: @"contactName"];
  }
  if (__contactPhone_isset)
  {
    [encoder encodeObject: __contactPhone forKey: @"contactPhone"];
  }
  if (__supplyOrder_isset)
  {
    [encoder encodeObject: __supplyOrder forKey: @"supplyOrder"];
  }
}

- (void) dealloc
{
  [__guest release_stub];
  [__contactName release_stub];
  [__contactPhone release_stub];
  [__supplyOrder release_stub];
  [super dealloc_stub];
}

- (int64_t) memberId {
  return __memberId;
}

- (void) setMemberId: (int64_t) memberId {
  __memberId = memberId;
  __memberId_isset = YES;
}

- (BOOL) memberIdIsSet {
  return __memberId_isset;
}

- (void) unsetMemberId {
  __memberId_isset = NO;
}

- (int32_t) hotelId {
  return __hotelId;
}

- (void) setHotelId: (int32_t) hotelId {
  __hotelId = hotelId;
  __hotelId_isset = YES;
}

- (BOOL) hotelIdIsSet {
  return __hotelId_isset;
}

- (void) unsetHotelId {
  __hotelId_isset = NO;
}

- (int32_t) roomId {
  return __roomId;
}

- (void) setRoomId: (int32_t) roomId {
  __roomId = roomId;
  __roomId_isset = YES;
}

- (BOOL) roomIdIsSet {
  return __roomId_isset;
}

- (void) unsetRoomId {
  __roomId_isset = NO;
}

- (int64_t) checkinTime {
  return __checkinTime;
}

- (void) setCheckinTime: (int64_t) checkinTime {
  __checkinTime = checkinTime;
  __checkinTime_isset = YES;
}

- (BOOL) checkinTimeIsSet {
  return __checkinTime_isset;
}

- (void) unsetCheckinTime {
  __checkinTime_isset = NO;
}

- (int64_t) checckoutTime {
  return __checckoutTime;
}

- (void) setChecckoutTime: (int64_t) checckoutTime {
  __checckoutTime = checckoutTime;
  __checckoutTime_isset = YES;
}

- (BOOL) checckoutTimeIsSet {
  return __checckoutTime_isset;
}

- (void) unsetChecckoutTime {
  __checckoutTime_isset = NO;
}

- (int32_t) roomNumber {
  return __roomNumber;
}

- (void) setRoomNumber: (int32_t) roomNumber {
  __roomNumber = roomNumber;
  __roomNumber_isset = YES;
}

- (BOOL) roomNumberIsSet {
  return __roomNumber_isset;
}

- (void) unsetRoomNumber {
  __roomNumber_isset = NO;
}

- (NSMutableArray *) guest {
  return [[__guest retain_stub] autorelease_stub];
}

- (void) setGuest: (NSMutableArray *) guest {
  [guest retain_stub];
  [__guest release_stub];
  __guest = guest;
  __guest_isset = YES;
}

- (BOOL) guestIsSet {
  return __guest_isset;
}

- (void) unsetGuest {
  [__guest release_stub];
  __guest = nil;
  __guest_isset = NO;
}

- (NSString *) contactName {
  return [[__contactName retain_stub] autorelease_stub];
}

- (void) setContactName: (NSString *) contactName {
  [contactName retain_stub];
  [__contactName release_stub];
  __contactName = contactName;
  __contactName_isset = YES;
}

- (BOOL) contactNameIsSet {
  return __contactName_isset;
}

- (void) unsetContactName {
  [__contactName release_stub];
  __contactName = nil;
  __contactName_isset = NO;
}

- (NSString *) contactPhone {
  return [[__contactPhone retain_stub] autorelease_stub];
}

- (void) setContactPhone: (NSString *) contactPhone {
  [contactPhone retain_stub];
  [__contactPhone release_stub];
  __contactPhone = contactPhone;
  __contactPhone_isset = YES;
}

- (BOOL) contactPhoneIsSet {
  return __contactPhone_isset;
}

- (void) unsetContactPhone {
  [__contactPhone release_stub];
  __contactPhone = nil;
  __contactPhone_isset = NO;
}

- (NSMutableArray *) supplyOrder {
  return [[__supplyOrder retain_stub] autorelease_stub];
}

- (void) setSupplyOrder: (NSMutableArray *) supplyOrder {
  [supplyOrder retain_stub];
  [__supplyOrder release_stub];
  __supplyOrder = supplyOrder;
  __supplyOrder_isset = YES;
}

- (BOOL) supplyOrderIsSet {
  return __supplyOrder_isset;
}

- (void) unsetSupplyOrder {
  [__supplyOrder release_stub];
  __supplyOrder = nil;
  __supplyOrder_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setMemberId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setHotelId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setRoomId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCheckinTime: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setChecckoutTime: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setRoomNumber: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_LIST) {
          int _size0;
          [inProtocol readListBeginReturningElementType: NULL size: &_size0];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            NSString * _elem2 = [inProtocol readString];
            [fieldValue addObject: _elem2];
          }
          [inProtocol readListEnd];
          [self setGuest: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 8:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setContactName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 9:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setContactPhone: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 10:
        if (fieldType == TType_LIST) {
          int _size3;
          [inProtocol readListBeginReturningElementType: NULL size: &_size3];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size3];
          int _i4;
          for (_i4 = 0; _i4 < _size3; ++_i4)
          {
            SupplyOrder *_elem5 = [[SupplyOrder alloc] init];
            [_elem5 read: inProtocol];
            [fieldValue addObject: _elem5];
            [_elem5 release_stub];
          }
          [inProtocol readListEnd];
          [self setSupplyOrder: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"BookingRequest"];
  if (__memberId_isset) {
    [outProtocol writeFieldBeginWithName: @"memberId" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __memberId];
    [outProtocol writeFieldEnd];
  }
  if (__hotelId_isset) {
    [outProtocol writeFieldBeginWithName: @"hotelId" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __hotelId];
    [outProtocol writeFieldEnd];
  }
  if (__roomId_isset) {
    [outProtocol writeFieldBeginWithName: @"roomId" type: TType_I32 fieldID: 3];
    [outProtocol writeI32: __roomId];
    [outProtocol writeFieldEnd];
  }
  if (__checkinTime_isset) {
    [outProtocol writeFieldBeginWithName: @"checkinTime" type: TType_I64 fieldID: 4];
    [outProtocol writeI64: __checkinTime];
    [outProtocol writeFieldEnd];
  }
  if (__checckoutTime_isset) {
    [outProtocol writeFieldBeginWithName: @"checckoutTime" type: TType_I64 fieldID: 5];
    [outProtocol writeI64: __checckoutTime];
    [outProtocol writeFieldEnd];
  }
  if (__roomNumber_isset) {
    [outProtocol writeFieldBeginWithName: @"roomNumber" type: TType_I32 fieldID: 6];
    [outProtocol writeI32: __roomNumber];
    [outProtocol writeFieldEnd];
  }
  if (__guest_isset) {
    if (__guest != nil) {
      [outProtocol writeFieldBeginWithName: @"guest" type: TType_LIST fieldID: 7];
      {
        [outProtocol writeListBeginWithElementType: TType_STRING size: [__guest count]];
        int i7;
        for (i7 = 0; i7 < [__guest count]; i7++)
        {
          [outProtocol writeString: [__guest objectAtIndex: i7]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__contactName_isset) {
    if (__contactName != nil) {
      [outProtocol writeFieldBeginWithName: @"contactName" type: TType_STRING fieldID: 8];
      [outProtocol writeString: __contactName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__contactPhone_isset) {
    if (__contactPhone != nil) {
      [outProtocol writeFieldBeginWithName: @"contactPhone" type: TType_STRING fieldID: 9];
      [outProtocol writeString: __contactPhone];
      [outProtocol writeFieldEnd];
    }
  }
  if (__supplyOrder_isset) {
    if (__supplyOrder != nil) {
      [outProtocol writeFieldBeginWithName: @"supplyOrder" type: TType_LIST fieldID: 10];
      {
        [outProtocol writeListBeginWithElementType: TType_STRUCT size: [__supplyOrder count]];
        int i9;
        for (i9 = 0; i9 < [__supplyOrder count]; i9++)
        {
          [[__supplyOrder objectAtIndex: i9] write: outProtocol];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"BookingRequest("];
  [ms appendString: @"memberId:"];
  [ms appendFormat: @"%qi", __memberId];
  [ms appendString: @",hotelId:"];
  [ms appendFormat: @"%i", __hotelId];
  [ms appendString: @",roomId:"];
  [ms appendFormat: @"%i", __roomId];
  [ms appendString: @",checkinTime:"];
  [ms appendFormat: @"%qi", __checkinTime];
  [ms appendString: @",checckoutTime:"];
  [ms appendFormat: @"%qi", __checckoutTime];
  [ms appendString: @",roomNumber:"];
  [ms appendFormat: @"%i", __roomNumber];
  [ms appendString: @",guest:"];
  [ms appendFormat: @"%@", __guest];
  [ms appendString: @",contactName:"];
  [ms appendFormat: @"\"%@\"", __contactName];
  [ms appendString: @",contactPhone:"];
  [ms appendFormat: @"\"%@\"", __contactPhone];
  [ms appendString: @",supplyOrder:"];
  [ms appendFormat: @"%@", __supplyOrder];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Reservation

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithReservationId: (int32_t) reservationId status: (int32_t) status hotelId: (int32_t) hotelId hotelName: (NSString *) hotelName hotelAddress: (NSString *) hotelAddress hotelPhone: (NSString *) hotelPhone checkinTime: (int64_t) checkinTime checkoutTime: (int64_t) checkoutTime roomId: (int32_t) roomId roomName: (NSString *) roomName roomNumber: (int32_t) roomNumber guest: (NSMutableArray *) guest contactName: (NSString *) contactName contactPhone: (NSString *) contactPhone totalPrice: (int32_t) totalPrice paymentStatus: (int32_t) paymentStatus cancelable: (BOOL) cancelable
{
  self = [super init];
  __reservationId = reservationId;
  __reservationId_isset = YES;
  __status = status;
  __status_isset = YES;
  __hotelId = hotelId;
  __hotelId_isset = YES;
  __hotelName = [hotelName retain_stub];
  __hotelName_isset = YES;
  __hotelAddress = [hotelAddress retain_stub];
  __hotelAddress_isset = YES;
  __hotelPhone = [hotelPhone retain_stub];
  __hotelPhone_isset = YES;
  __checkinTime = checkinTime;
  __checkinTime_isset = YES;
  __checkoutTime = checkoutTime;
  __checkoutTime_isset = YES;
  __roomId = roomId;
  __roomId_isset = YES;
  __roomName = [roomName retain_stub];
  __roomName_isset = YES;
  __roomNumber = roomNumber;
  __roomNumber_isset = YES;
  __guest = [guest retain_stub];
  __guest_isset = YES;
  __contactName = [contactName retain_stub];
  __contactName_isset = YES;
  __contactPhone = [contactPhone retain_stub];
  __contactPhone_isset = YES;
  __totalPrice = totalPrice;
  __totalPrice_isset = YES;
  __paymentStatus = paymentStatus;
  __paymentStatus_isset = YES;
  __cancelable = cancelable;
  __cancelable_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"reservationId"])
  {
    __reservationId = [decoder decodeInt32ForKey: @"reservationId"];
    __reservationId_isset = YES;
  }
  if ([decoder containsValueForKey: @"status"])
  {
    __status = [decoder decodeInt32ForKey: @"status"];
    __status_isset = YES;
  }
  if ([decoder containsValueForKey: @"hotelId"])
  {
    __hotelId = [decoder decodeInt32ForKey: @"hotelId"];
    __hotelId_isset = YES;
  }
  if ([decoder containsValueForKey: @"hotelName"])
  {
    __hotelName = [[decoder decodeObjectForKey: @"hotelName"] retain_stub];
    __hotelName_isset = YES;
  }
  if ([decoder containsValueForKey: @"hotelAddress"])
  {
    __hotelAddress = [[decoder decodeObjectForKey: @"hotelAddress"] retain_stub];
    __hotelAddress_isset = YES;
  }
  if ([decoder containsValueForKey: @"hotelPhone"])
  {
    __hotelPhone = [[decoder decodeObjectForKey: @"hotelPhone"] retain_stub];
    __hotelPhone_isset = YES;
  }
  if ([decoder containsValueForKey: @"checkinTime"])
  {
    __checkinTime = [decoder decodeInt64ForKey: @"checkinTime"];
    __checkinTime_isset = YES;
  }
  if ([decoder containsValueForKey: @"checkoutTime"])
  {
    __checkoutTime = [decoder decodeInt64ForKey: @"checkoutTime"];
    __checkoutTime_isset = YES;
  }
  if ([decoder containsValueForKey: @"roomId"])
  {
    __roomId = [decoder decodeInt32ForKey: @"roomId"];
    __roomId_isset = YES;
  }
  if ([decoder containsValueForKey: @"roomName"])
  {
    __roomName = [[decoder decodeObjectForKey: @"roomName"] retain_stub];
    __roomName_isset = YES;
  }
  if ([decoder containsValueForKey: @"roomNumber"])
  {
    __roomNumber = [decoder decodeInt32ForKey: @"roomNumber"];
    __roomNumber_isset = YES;
  }
  if ([decoder containsValueForKey: @"guest"])
  {
    __guest = [[decoder decodeObjectForKey: @"guest"] retain_stub];
    __guest_isset = YES;
  }
  if ([decoder containsValueForKey: @"contactName"])
  {
    __contactName = [[decoder decodeObjectForKey: @"contactName"] retain_stub];
    __contactName_isset = YES;
  }
  if ([decoder containsValueForKey: @"contactPhone"])
  {
    __contactPhone = [[decoder decodeObjectForKey: @"contactPhone"] retain_stub];
    __contactPhone_isset = YES;
  }
  if ([decoder containsValueForKey: @"totalPrice"])
  {
    __totalPrice = [decoder decodeInt32ForKey: @"totalPrice"];
    __totalPrice_isset = YES;
  }
  if ([decoder containsValueForKey: @"paymentStatus"])
  {
    __paymentStatus = [decoder decodeInt32ForKey: @"paymentStatus"];
    __paymentStatus_isset = YES;
  }
  if ([decoder containsValueForKey: @"cancelable"])
  {
    __cancelable = [decoder decodeBoolForKey: @"cancelable"];
    __cancelable_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__reservationId_isset)
  {
    [encoder encodeInt32: __reservationId forKey: @"reservationId"];
  }
  if (__status_isset)
  {
    [encoder encodeInt32: __status forKey: @"status"];
  }
  if (__hotelId_isset)
  {
    [encoder encodeInt32: __hotelId forKey: @"hotelId"];
  }
  if (__hotelName_isset)
  {
    [encoder encodeObject: __hotelName forKey: @"hotelName"];
  }
  if (__hotelAddress_isset)
  {
    [encoder encodeObject: __hotelAddress forKey: @"hotelAddress"];
  }
  if (__hotelPhone_isset)
  {
    [encoder encodeObject: __hotelPhone forKey: @"hotelPhone"];
  }
  if (__checkinTime_isset)
  {
    [encoder encodeInt64: __checkinTime forKey: @"checkinTime"];
  }
  if (__checkoutTime_isset)
  {
    [encoder encodeInt64: __checkoutTime forKey: @"checkoutTime"];
  }
  if (__roomId_isset)
  {
    [encoder encodeInt32: __roomId forKey: @"roomId"];
  }
  if (__roomName_isset)
  {
    [encoder encodeObject: __roomName forKey: @"roomName"];
  }
  if (__roomNumber_isset)
  {
    [encoder encodeInt32: __roomNumber forKey: @"roomNumber"];
  }
  if (__guest_isset)
  {
    [encoder encodeObject: __guest forKey: @"guest"];
  }
  if (__contactName_isset)
  {
    [encoder encodeObject: __contactName forKey: @"contactName"];
  }
  if (__contactPhone_isset)
  {
    [encoder encodeObject: __contactPhone forKey: @"contactPhone"];
  }
  if (__totalPrice_isset)
  {
    [encoder encodeInt32: __totalPrice forKey: @"totalPrice"];
  }
  if (__paymentStatus_isset)
  {
    [encoder encodeInt32: __paymentStatus forKey: @"paymentStatus"];
  }
  if (__cancelable_isset)
  {
    [encoder encodeBool: __cancelable forKey: @"cancelable"];
  }
}

- (void) dealloc
{
  [__hotelName release_stub];
  [__hotelAddress release_stub];
  [__hotelPhone release_stub];
  [__roomName release_stub];
  [__guest release_stub];
  [__contactName release_stub];
  [__contactPhone release_stub];
  [super dealloc_stub];
}

- (int32_t) reservationId {
  return __reservationId;
}

- (void) setReservationId: (int32_t) reservationId {
  __reservationId = reservationId;
  __reservationId_isset = YES;
}

- (BOOL) reservationIdIsSet {
  return __reservationId_isset;
}

- (void) unsetReservationId {
  __reservationId_isset = NO;
}

- (int32_t) status {
  return __status;
}

- (void) setStatus: (int32_t) status {
  __status = status;
  __status_isset = YES;
}

- (BOOL) statusIsSet {
  return __status_isset;
}

- (void) unsetStatus {
  __status_isset = NO;
}

- (int32_t) hotelId {
  return __hotelId;
}

- (void) setHotelId: (int32_t) hotelId {
  __hotelId = hotelId;
  __hotelId_isset = YES;
}

- (BOOL) hotelIdIsSet {
  return __hotelId_isset;
}

- (void) unsetHotelId {
  __hotelId_isset = NO;
}

- (NSString *) hotelName {
  return [[__hotelName retain_stub] autorelease_stub];
}

- (void) setHotelName: (NSString *) hotelName {
  [hotelName retain_stub];
  [__hotelName release_stub];
  __hotelName = hotelName;
  __hotelName_isset = YES;
}

- (BOOL) hotelNameIsSet {
  return __hotelName_isset;
}

- (void) unsetHotelName {
  [__hotelName release_stub];
  __hotelName = nil;
  __hotelName_isset = NO;
}

- (NSString *) hotelAddress {
  return [[__hotelAddress retain_stub] autorelease_stub];
}

- (void) setHotelAddress: (NSString *) hotelAddress {
  [hotelAddress retain_stub];
  [__hotelAddress release_stub];
  __hotelAddress = hotelAddress;
  __hotelAddress_isset = YES;
}

- (BOOL) hotelAddressIsSet {
  return __hotelAddress_isset;
}

- (void) unsetHotelAddress {
  [__hotelAddress release_stub];
  __hotelAddress = nil;
  __hotelAddress_isset = NO;
}

- (NSString *) hotelPhone {
  return [[__hotelPhone retain_stub] autorelease_stub];
}

- (void) setHotelPhone: (NSString *) hotelPhone {
  [hotelPhone retain_stub];
  [__hotelPhone release_stub];
  __hotelPhone = hotelPhone;
  __hotelPhone_isset = YES;
}

- (BOOL) hotelPhoneIsSet {
  return __hotelPhone_isset;
}

- (void) unsetHotelPhone {
  [__hotelPhone release_stub];
  __hotelPhone = nil;
  __hotelPhone_isset = NO;
}

- (int64_t) checkinTime {
  return __checkinTime;
}

- (void) setCheckinTime: (int64_t) checkinTime {
  __checkinTime = checkinTime;
  __checkinTime_isset = YES;
}

- (BOOL) checkinTimeIsSet {
  return __checkinTime_isset;
}

- (void) unsetCheckinTime {
  __checkinTime_isset = NO;
}

- (int64_t) checkoutTime {
  return __checkoutTime;
}

- (void) setCheckoutTime: (int64_t) checkoutTime {
  __checkoutTime = checkoutTime;
  __checkoutTime_isset = YES;
}

- (BOOL) checkoutTimeIsSet {
  return __checkoutTime_isset;
}

- (void) unsetCheckoutTime {
  __checkoutTime_isset = NO;
}

- (int32_t) roomId {
  return __roomId;
}

- (void) setRoomId: (int32_t) roomId {
  __roomId = roomId;
  __roomId_isset = YES;
}

- (BOOL) roomIdIsSet {
  return __roomId_isset;
}

- (void) unsetRoomId {
  __roomId_isset = NO;
}

- (NSString *) roomName {
  return [[__roomName retain_stub] autorelease_stub];
}

- (void) setRoomName: (NSString *) roomName {
  [roomName retain_stub];
  [__roomName release_stub];
  __roomName = roomName;
  __roomName_isset = YES;
}

- (BOOL) roomNameIsSet {
  return __roomName_isset;
}

- (void) unsetRoomName {
  [__roomName release_stub];
  __roomName = nil;
  __roomName_isset = NO;
}

- (int32_t) roomNumber {
  return __roomNumber;
}

- (void) setRoomNumber: (int32_t) roomNumber {
  __roomNumber = roomNumber;
  __roomNumber_isset = YES;
}

- (BOOL) roomNumberIsSet {
  return __roomNumber_isset;
}

- (void) unsetRoomNumber {
  __roomNumber_isset = NO;
}

- (NSMutableArray *) guest {
  return [[__guest retain_stub] autorelease_stub];
}

- (void) setGuest: (NSMutableArray *) guest {
  [guest retain_stub];
  [__guest release_stub];
  __guest = guest;
  __guest_isset = YES;
}

- (BOOL) guestIsSet {
  return __guest_isset;
}

- (void) unsetGuest {
  [__guest release_stub];
  __guest = nil;
  __guest_isset = NO;
}

- (NSString *) contactName {
  return [[__contactName retain_stub] autorelease_stub];
}

- (void) setContactName: (NSString *) contactName {
  [contactName retain_stub];
  [__contactName release_stub];
  __contactName = contactName;
  __contactName_isset = YES;
}

- (BOOL) contactNameIsSet {
  return __contactName_isset;
}

- (void) unsetContactName {
  [__contactName release_stub];
  __contactName = nil;
  __contactName_isset = NO;
}

- (NSString *) contactPhone {
  return [[__contactPhone retain_stub] autorelease_stub];
}

- (void) setContactPhone: (NSString *) contactPhone {
  [contactPhone retain_stub];
  [__contactPhone release_stub];
  __contactPhone = contactPhone;
  __contactPhone_isset = YES;
}

- (BOOL) contactPhoneIsSet {
  return __contactPhone_isset;
}

- (void) unsetContactPhone {
  [__contactPhone release_stub];
  __contactPhone = nil;
  __contactPhone_isset = NO;
}

- (int32_t) totalPrice {
  return __totalPrice;
}

- (void) setTotalPrice: (int32_t) totalPrice {
  __totalPrice = totalPrice;
  __totalPrice_isset = YES;
}

- (BOOL) totalPriceIsSet {
  return __totalPrice_isset;
}

- (void) unsetTotalPrice {
  __totalPrice_isset = NO;
}

- (int32_t) paymentStatus {
  return __paymentStatus;
}

- (void) setPaymentStatus: (int32_t) paymentStatus {
  __paymentStatus = paymentStatus;
  __paymentStatus_isset = YES;
}

- (BOOL) paymentStatusIsSet {
  return __paymentStatus_isset;
}

- (void) unsetPaymentStatus {
  __paymentStatus_isset = NO;
}

- (BOOL) cancelable {
  return __cancelable;
}

- (void) setCancelable: (BOOL) cancelable {
  __cancelable = cancelable;
  __cancelable_isset = YES;
}

- (BOOL) cancelableIsSet {
  return __cancelable_isset;
}

- (void) unsetCancelable {
  __cancelable_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setReservationId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setStatus: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setHotelId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setHotelName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setHotelAddress: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setHotelPhone: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCheckinTime: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 8:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCheckoutTime: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 9:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setRoomId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 10:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setRoomName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 11:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setRoomNumber: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 12:
        if (fieldType == TType_LIST) {
          int _size10;
          [inProtocol readListBeginReturningElementType: NULL size: &_size10];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size10];
          int _i11;
          for (_i11 = 0; _i11 < _size10; ++_i11)
          {
            NSString * _elem12 = [inProtocol readString];
            [fieldValue addObject: _elem12];
          }
          [inProtocol readListEnd];
          [self setGuest: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 13:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setContactName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 14:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setContactPhone: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 15:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setTotalPrice: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 16:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setPaymentStatus: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 17:
        if (fieldType == TType_BOOL) {
          BOOL fieldValue = [inProtocol readBool];
          [self setCancelable: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Reservation"];
  if (__reservationId_isset) {
    [outProtocol writeFieldBeginWithName: @"reservationId" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __reservationId];
    [outProtocol writeFieldEnd];
  }
  if (__status_isset) {
    [outProtocol writeFieldBeginWithName: @"status" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __status];
    [outProtocol writeFieldEnd];
  }
  if (__hotelId_isset) {
    [outProtocol writeFieldBeginWithName: @"hotelId" type: TType_I32 fieldID: 3];
    [outProtocol writeI32: __hotelId];
    [outProtocol writeFieldEnd];
  }
  if (__hotelName_isset) {
    if (__hotelName != nil) {
      [outProtocol writeFieldBeginWithName: @"hotelName" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __hotelName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__hotelAddress_isset) {
    if (__hotelAddress != nil) {
      [outProtocol writeFieldBeginWithName: @"hotelAddress" type: TType_STRING fieldID: 5];
      [outProtocol writeString: __hotelAddress];
      [outProtocol writeFieldEnd];
    }
  }
  if (__hotelPhone_isset) {
    if (__hotelPhone != nil) {
      [outProtocol writeFieldBeginWithName: @"hotelPhone" type: TType_STRING fieldID: 6];
      [outProtocol writeString: __hotelPhone];
      [outProtocol writeFieldEnd];
    }
  }
  if (__checkinTime_isset) {
    [outProtocol writeFieldBeginWithName: @"checkinTime" type: TType_I64 fieldID: 7];
    [outProtocol writeI64: __checkinTime];
    [outProtocol writeFieldEnd];
  }
  if (__checkoutTime_isset) {
    [outProtocol writeFieldBeginWithName: @"checkoutTime" type: TType_I64 fieldID: 8];
    [outProtocol writeI64: __checkoutTime];
    [outProtocol writeFieldEnd];
  }
  if (__roomId_isset) {
    [outProtocol writeFieldBeginWithName: @"roomId" type: TType_I32 fieldID: 9];
    [outProtocol writeI32: __roomId];
    [outProtocol writeFieldEnd];
  }
  if (__roomName_isset) {
    if (__roomName != nil) {
      [outProtocol writeFieldBeginWithName: @"roomName" type: TType_STRING fieldID: 10];
      [outProtocol writeString: __roomName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__roomNumber_isset) {
    [outProtocol writeFieldBeginWithName: @"roomNumber" type: TType_I32 fieldID: 11];
    [outProtocol writeI32: __roomNumber];
    [outProtocol writeFieldEnd];
  }
  if (__guest_isset) {
    if (__guest != nil) {
      [outProtocol writeFieldBeginWithName: @"guest" type: TType_LIST fieldID: 12];
      {
        [outProtocol writeListBeginWithElementType: TType_STRING size: [__guest count]];
        int i14;
        for (i14 = 0; i14 < [__guest count]; i14++)
        {
          [outProtocol writeString: [__guest objectAtIndex: i14]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__contactName_isset) {
    if (__contactName != nil) {
      [outProtocol writeFieldBeginWithName: @"contactName" type: TType_STRING fieldID: 13];
      [outProtocol writeString: __contactName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__contactPhone_isset) {
    if (__contactPhone != nil) {
      [outProtocol writeFieldBeginWithName: @"contactPhone" type: TType_STRING fieldID: 14];
      [outProtocol writeString: __contactPhone];
      [outProtocol writeFieldEnd];
    }
  }
  if (__totalPrice_isset) {
    [outProtocol writeFieldBeginWithName: @"totalPrice" type: TType_I32 fieldID: 15];
    [outProtocol writeI32: __totalPrice];
    [outProtocol writeFieldEnd];
  }
  if (__paymentStatus_isset) {
    [outProtocol writeFieldBeginWithName: @"paymentStatus" type: TType_I32 fieldID: 16];
    [outProtocol writeI32: __paymentStatus];
    [outProtocol writeFieldEnd];
  }
  if (__cancelable_isset) {
    [outProtocol writeFieldBeginWithName: @"cancelable" type: TType_BOOL fieldID: 17];
    [outProtocol writeBool: __cancelable];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Reservation("];
  [ms appendString: @"reservationId:"];
  [ms appendFormat: @"%i", __reservationId];
  [ms appendString: @",status:"];
  [ms appendFormat: @"%i", __status];
  [ms appendString: @",hotelId:"];
  [ms appendFormat: @"%i", __hotelId];
  [ms appendString: @",hotelName:"];
  [ms appendFormat: @"\"%@\"", __hotelName];
  [ms appendString: @",hotelAddress:"];
  [ms appendFormat: @"\"%@\"", __hotelAddress];
  [ms appendString: @",hotelPhone:"];
  [ms appendFormat: @"\"%@\"", __hotelPhone];
  [ms appendString: @",checkinTime:"];
  [ms appendFormat: @"%qi", __checkinTime];
  [ms appendString: @",checkoutTime:"];
  [ms appendFormat: @"%qi", __checkoutTime];
  [ms appendString: @",roomId:"];
  [ms appendFormat: @"%i", __roomId];
  [ms appendString: @",roomName:"];
  [ms appendFormat: @"\"%@\"", __roomName];
  [ms appendString: @",roomNumber:"];
  [ms appendFormat: @"%i", __roomNumber];
  [ms appendString: @",guest:"];
  [ms appendFormat: @"%@", __guest];
  [ms appendString: @",contactName:"];
  [ms appendFormat: @"\"%@\"", __contactName];
  [ms appendString: @",contactPhone:"];
  [ms appendFormat: @"\"%@\"", __contactPhone];
  [ms appendString: @",totalPrice:"];
  [ms appendFormat: @"%i", __totalPrice];
  [ms appendString: @",paymentStatus:"];
  [ms appendFormat: @"%i", __paymentStatus];
  [ms appendString: @",cancelable:"];
  [ms appendFormat: @"%i", __cancelable];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation TBookingConstants
+ (void) initialize {
}
@end

