/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


@interface SupplyOrder : NSObject <NSCoding> {
  int32_t __supplyId;
  int32_t __quantity;

  BOOL __supplyId_isset;
  BOOL __quantity_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=supplyId, setter=setSupplyId:) int32_t supplyId;
@property (nonatomic, getter=quantity, setter=setQuantity:) int32_t quantity;
#endif

- (id) init;
- (id) initWithSupplyId: (int32_t) supplyId quantity: (int32_t) quantity;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int32_t) supplyId;
- (void) setSupplyId: (int32_t) supplyId;
#endif
- (BOOL) supplyIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) quantity;
- (void) setQuantity: (int32_t) quantity;
#endif
- (BOOL) quantityIsSet;

@end

@interface BookingRequest : NSObject <NSCoding> {
  int64_t __memberId;
  int32_t __hotelId;
  int32_t __roomId;
  int64_t __checkinTime;
  int64_t __checckoutTime;
  int32_t __roomNumber;
  NSMutableArray * __guest;
  NSString * __contactName;
  NSString * __contactPhone;
  NSMutableArray * __supplyOrder;

  BOOL __memberId_isset;
  BOOL __hotelId_isset;
  BOOL __roomId_isset;
  BOOL __checkinTime_isset;
  BOOL __checckoutTime_isset;
  BOOL __roomNumber_isset;
  BOOL __guest_isset;
  BOOL __contactName_isset;
  BOOL __contactPhone_isset;
  BOOL __supplyOrder_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=memberId, setter=setMemberId:) int64_t memberId;
@property (nonatomic, getter=hotelId, setter=setHotelId:) int32_t hotelId;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, getter=checkinTime, setter=setCheckinTime:) int64_t checkinTime;
@property (nonatomic, getter=checckoutTime, setter=setChecckoutTime:) int64_t checckoutTime;
@property (nonatomic, getter=roomNumber, setter=setRoomNumber:) int32_t roomNumber;
@property (nonatomic, retain, getter=guest, setter=setGuest:) NSMutableArray * guest;
@property (nonatomic, retain, getter=contactName, setter=setContactName:) NSString * contactName;
@property (nonatomic, retain, getter=contactPhone, setter=setContactPhone:) NSString * contactPhone;
@property (nonatomic, retain, getter=supplyOrder, setter=setSupplyOrder:) NSMutableArray * supplyOrder;
#endif

- (id) init;
- (id) initWithMemberId: (int64_t) memberId hotelId: (int32_t) hotelId roomId: (int32_t) roomId checkinTime: (int64_t) checkinTime checckoutTime: (int64_t) checckoutTime roomNumber: (int32_t) roomNumber guest: (NSMutableArray *) guest contactName: (NSString *) contactName contactPhone: (NSString *) contactPhone supplyOrder: (NSMutableArray *) supplyOrder;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) memberId;
- (void) setMemberId: (int64_t) memberId;
#endif
- (BOOL) memberIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) hotelId;
- (void) setHotelId: (int32_t) hotelId;
#endif
- (BOOL) hotelIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
#endif
- (BOOL) roomIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checkinTime;
- (void) setCheckinTime: (int64_t) checkinTime;
#endif
- (BOOL) checkinTimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checckoutTime;
- (void) setChecckoutTime: (int64_t) checckoutTime;
#endif
- (BOOL) checckoutTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) roomNumber;
- (void) setRoomNumber: (int32_t) roomNumber;
#endif
- (BOOL) roomNumberIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) guest;
- (void) setGuest: (NSMutableArray *) guest;
#endif
- (BOOL) guestIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contactName;
- (void) setContactName: (NSString *) contactName;
#endif
- (BOOL) contactNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contactPhone;
- (void) setContactPhone: (NSString *) contactPhone;
#endif
- (BOOL) contactPhoneIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) supplyOrder;
- (void) setSupplyOrder: (NSMutableArray *) supplyOrder;
#endif
- (BOOL) supplyOrderIsSet;

@end

@interface Reservation : NSObject <NSCoding> {
  int32_t __reservationId;
  int32_t __status;
  int32_t __hotelId;
  NSString * __hotelName;
  NSString * __hotelAddress;
  NSString * __hotelPhone;
  int64_t __checkinTime;
  int64_t __checkoutTime;
  int32_t __roomId;
  NSString * __roomName;
  int32_t __roomNumber;
  NSMutableArray * __guest;
  NSString * __contactName;
  NSString * __contactPhone;
  int32_t __totalPrice;
  int32_t __paymentStatus;
  BOOL __cancelable;

  BOOL __reservationId_isset;
  BOOL __status_isset;
  BOOL __hotelId_isset;
  BOOL __hotelName_isset;
  BOOL __hotelAddress_isset;
  BOOL __hotelPhone_isset;
  BOOL __checkinTime_isset;
  BOOL __checkoutTime_isset;
  BOOL __roomId_isset;
  BOOL __roomName_isset;
  BOOL __roomNumber_isset;
  BOOL __guest_isset;
  BOOL __contactName_isset;
  BOOL __contactPhone_isset;
  BOOL __totalPrice_isset;
  BOOL __paymentStatus_isset;
  BOOL __cancelable_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=reservationId, setter=setReservationId:) int32_t reservationId;
@property (nonatomic, getter=status, setter=setStatus:) int32_t status;
@property (nonatomic, getter=hotelId, setter=setHotelId:) int32_t hotelId;
@property (nonatomic, retain, getter=hotelName, setter=setHotelName:) NSString * hotelName;
@property (nonatomic, retain, getter=hotelAddress, setter=setHotelAddress:) NSString * hotelAddress;
@property (nonatomic, retain, getter=hotelPhone, setter=setHotelPhone:) NSString * hotelPhone;
@property (nonatomic, getter=checkinTime, setter=setCheckinTime:) int64_t checkinTime;
@property (nonatomic, getter=checkoutTime, setter=setCheckoutTime:) int64_t checkoutTime;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, retain, getter=roomName, setter=setRoomName:) NSString * roomName;
@property (nonatomic, getter=roomNumber, setter=setRoomNumber:) int32_t roomNumber;
@property (nonatomic, retain, getter=guest, setter=setGuest:) NSMutableArray * guest;
@property (nonatomic, retain, getter=contactName, setter=setContactName:) NSString * contactName;
@property (nonatomic, retain, getter=contactPhone, setter=setContactPhone:) NSString * contactPhone;
@property (nonatomic, getter=totalPrice, setter=setTotalPrice:) int32_t totalPrice;
@property (nonatomic, getter=paymentStatus, setter=setPaymentStatus:) int32_t paymentStatus;
@property (nonatomic, getter=cancelable, setter=setCancelable:) BOOL cancelable;
#endif

- (id) init;
- (id) initWithReservationId: (int32_t) reservationId status: (int32_t) status hotelId: (int32_t) hotelId hotelName: (NSString *) hotelName hotelAddress: (NSString *) hotelAddress hotelPhone: (NSString *) hotelPhone checkinTime: (int64_t) checkinTime checkoutTime: (int64_t) checkoutTime roomId: (int32_t) roomId roomName: (NSString *) roomName roomNumber: (int32_t) roomNumber guest: (NSMutableArray *) guest contactName: (NSString *) contactName contactPhone: (NSString *) contactPhone totalPrice: (int32_t) totalPrice paymentStatus: (int32_t) paymentStatus cancelable: (BOOL) cancelable;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int32_t) reservationId;
- (void) setReservationId: (int32_t) reservationId;
#endif
- (BOOL) reservationIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) status;
- (void) setStatus: (int32_t) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (int32_t) hotelId;
- (void) setHotelId: (int32_t) hotelId;
#endif
- (BOOL) hotelIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hotelName;
- (void) setHotelName: (NSString *) hotelName;
#endif
- (BOOL) hotelNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hotelAddress;
- (void) setHotelAddress: (NSString *) hotelAddress;
#endif
- (BOOL) hotelAddressIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hotelPhone;
- (void) setHotelPhone: (NSString *) hotelPhone;
#endif
- (BOOL) hotelPhoneIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checkinTime;
- (void) setCheckinTime: (int64_t) checkinTime;
#endif
- (BOOL) checkinTimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) checkoutTime;
- (void) setCheckoutTime: (int64_t) checkoutTime;
#endif
- (BOOL) checkoutTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
#endif
- (BOOL) roomIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) roomName;
- (void) setRoomName: (NSString *) roomName;
#endif
- (BOOL) roomNameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) roomNumber;
- (void) setRoomNumber: (int32_t) roomNumber;
#endif
- (BOOL) roomNumberIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) guest;
- (void) setGuest: (NSMutableArray *) guest;
#endif
- (BOOL) guestIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contactName;
- (void) setContactName: (NSString *) contactName;
#endif
- (BOOL) contactNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contactPhone;
- (void) setContactPhone: (NSString *) contactPhone;
#endif
- (BOOL) contactPhoneIsSet;

#if !__has_feature(objc_arc)
- (int32_t) totalPrice;
- (void) setTotalPrice: (int32_t) totalPrice;
#endif
- (BOOL) totalPriceIsSet;

#if !__has_feature(objc_arc)
- (int32_t) paymentStatus;
- (void) setPaymentStatus: (int32_t) paymentStatus;
#endif
- (BOOL) paymentStatusIsSet;

#if !__has_feature(objc_arc)
- (BOOL) cancelable;
- (void) setCancelable: (BOOL) cancelable;
#endif
- (BOOL) cancelableIsSet;

@end

@interface TBookingConstants : NSObject {
}
@end
